### PR TITLE
Readme - add installed apps and allowed hosts

### PR DESCRIPTION
**Pull request by collingreen**
Update readme with additional required setup steps.

### CODE REVIEW

**Comment by mathom** [comment]
I was going to make an issue for this but since you guys are working on the README in here I figured I'd drop by with a comment: 

I'm far from a django expert, but I think this might be a better way to refer to the `settings_file` in the config:

```python
       'settings_file': os.path.join(BASE_DIR, 'MyApp', 'settings.py'),
```

I'm not sure if it's specific to a certain version of django but my settings files have always had `BASE_DIR` defined out of the box.

**Comment by collingreen** [comment]
@mathom - I think this discussion is happening at this very moment on https://github.com/Miserlou/django-zappa/issues/29

**Comment by collingreen** [comment]
This will be closed in favor of a change containing only the INSTALLED_APPS part.

**Comment by collingreen** [comment]
Replaced by https://github.com/Miserlou/django-zappa/pull/33

**Pull request closed without merging**
